trigger:
  branches:
    include:
      - main

parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: apply
  values:
    - apply
    - destroy

variables:
  TF_VERSION: "1.6.6"
  AWS_REGION: "us-east-1"
  TF_STATE_BUCKET: "nti-terraform-states"
  TF_STATE_KEY: "eks/terraform.tfstate"

pool:
  name: Self hosted pools
  demands:
    - agent.name -equals ip-172-31-39-167

stages:
- stage: Terraform
  displayName: Terraform Infrastructure
  jobs:
  - job: TerraformJob
    displayName: Terraform Apply or Destroy
    steps:

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)

    # -------------------------
    # Terraform Init (S3 backend)
    # -------------------------
    - script: |
        cd Cluster
        terraform init \
          -backend-config="bucket=$(TF_STATE_BUCKET)" \
          -backend-config="key=$(TF_STATE_KEY)" \
          -backend-config="region=$(AWS_REGION)"
      displayName: Terraform Init

    - script: |
        cd Cluster
        terraform validate
      displayName: Terraform Validate

    - script: |
        cd Cluster
        terraform plan -out=tfplan
      displayName: Terraform Plan

    - ${{ if eq(parameters.action, 'apply') }}:
      - script: |
          cd Cluster
          terraform apply -auto-approve tfplan
        displayName: Terraform Apply

    - ${{ if eq(parameters.action, 'destroy') }}:
      - script: |
          cd Cluster
          terraform destroy -auto-approve
        displayName: Terraform Destroy
